### ISSUE TITLE
After pressing one of the question buttons, the numbers transform to a wide "play" button

### ISSUE THREAD

**Issue by lheinl1710** [concise-ee/superagile_app#25]
The numbers 0, 1, 2, 3 transform to a wide "play" button in the shape of a sideways triangle, which, when pressed, will redirect to the question results page.

**Comment by roosi-ann** [comment]
Decided on a simpler version:
For usual player: 
1. Every player selects an answer
2. that answer is highlighted (and may be changed until everybody else answers) 
3. After everybody has answered, answers page is shown. 
For host
1. If not playing along, show question page version where instead of answers there is a play button. That button is disabled until everybody else has answered. Pressing that button takes everybody to the answers page.
2. After everyone has answered, show the answers page. If everybody doesn't have the same answer, show button to start next voting round (answer the same question again)

**Comment by TheAngryDuck** [comment]
Decided to have the play button above the other options for the host that is playing along. This would only be there for only the first few iteration of the app

**Comment by jakobpin** [comment]
First usable version implemented in host/player sync issues
